name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

env:
  ALERT_THRESHOLD_RSI_OVERBOUGHT: ${{ vars.ALERT_THRESHOLD_RSI_OVERBOUGHT }}
  ALERT_THRESHOLD_RSI_OVERSOLD: ${{ vars.ALERT_THRESHOLD_RSI_OVERSOLD }}
  ALERT_THRESHOLD_VOLUME_SPIKE: ${{ vars.ALERT_THRESHOLD_VOLUME_SPIKE }}

jobs:
  build-and-test:
    runs-on: [self-hosted, ARM64, TradingBot]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
        install-dir: ${{ runner.temp }}/dotnet

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --configuration Release

  deploy:
    needs: build-and-test
    runs-on: [self-hosted, ARM64, TradingBot]

    steps:
    - name: Deploy application
      run: |
        echo "Deploying on Raspberry Pi using self-hosted runner"
        # Comandos de deploy apropriados
